# version: '3'

# services:
#   api:
#     build:
#       context: ./api
#     networks:
#       - custom_network
#     ports:
#       - 3000:3000
#     environment:
#       DB_HOST: db
#       DB_PORT: 27017
#       DB_NAME: usermanagementdb
#     depends_on:
#       - db
#     volumes:
#       - .:/home/node/app
#       - node_modules:/home/node/app/node_modules

#   client:
#     build:
#       context: ./client
#     ports:
#       - 8080:8080

#   db:
#     image: mongo:4.1.8-xenial
#     container_name: db
#     networks:
#       - custom_network
#     ports:
#       - 27017:27017
#     volumes:
#       - db:/data/db

# networks:
#   custom_network:

# volumes:
#   db:
#   node_modules:

version: '3'
services:
  api:
    container_name: api
    build:
      context: ./api
    depends_on:
      - db
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
    environment:
      - MONGO_URL=mongodb://db:27017/usermanagementdb
      - APP_PORT=3000
    ports: ['3000:3000']

  db:
    container_name: db
    image: mongo:4.0
    restart: always

  client:
    container_name: client
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:
      - BACKEND_URL=http://localhost/todos
